#Requires -Version 5.1
<#
.SYNOPSIS
	Prepares files required to build the installer.

.DESCRIPTION
	Prepare
		Collects files to install into payload.zip,
		and generates instinfo.h containing version info.
		Called from pre-build event of Installer.vcxproj.
	Publish
		Outputs built installer as clcl<version>.exe.
		Called from post-build event of Installer.vcxproj.

	Usually executed via Visual Studio project from build.ps1.
#>
param(
	# Operation
	[ValidateSet("Prepare", "Publish")]
	[string]$Mode = "Prepare",
	# Prepare: output folder for generated files / Publish: destination folder
	[string]$OutDir = "",
	# Build configuration
	[string]$Configuration = "Release",
	# Source directory for installed files (default: <repo>\<Configuration>)
	[string]$SourceDir = "",
	# Version (default: uses FILEVERSION from CLCL.rc)
	[string]$Version = "",
	# Publish: path to built installer
	[string]$TargetPath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$InstallerDir = $PSScriptRoot
$RootDir = Split-Path -Parent $InstallerDir

# Get version
function Get-ClclVersion([string]$specified) {
	if (-not [string]::IsNullOrEmpty($specified)) {
		$m = [regex]::Match($specified, '^(\d+)\.(\d+)\.(\d+)$')
		if (-not $m.Success) {
			throw "Invalid version specified (e.g. 2.2.0): $specified"
		}
	} else {
		$rcPath = Join-Path $RootDir "CLCL.rc"
		if (-not (Test-Path $rcPath)) {
			throw "CLCL.rc not found: $rcPath"
		}
		$rcText = Get-Content -Path $rcPath -Raw -Encoding UTF8
		$m = [regex]::Match($rcText, 'FILEVERSION\s+(\d+)\s*,\s*(\d+)\s*,\s*(\d+)')
		if (-not $m.Success) {
			throw "Failed to get FILEVERSION from CLCL.rc."
		}
	}
	$major = [int]$m.Groups[1].Value
	$minor = [int]$m.Groups[2].Value
	$revision = [int]$m.Groups[3].Value
	return [pscustomobject]@{
		Major    = $major
		Minor    = $minor
		Revision = $revision
		Text     = "$major.$minor.$revision"
		FileName = "clcl$major$minor$revision.exe"
	}
}

# Files to install (source path = installed file name)
function Get-TargetFiles([string]$binDir) {
	return [ordered]@{
		(Join-Path $binDir "CLCL.exe")        = "CLCL.exe"
		(Join-Path $binDir "CLCLSet.exe")     = "CLCLSet.exe"
		(Join-Path $binDir "CLCLHook.dll")    = "CLCLHook.dll"
		(Join-Path $RootDir "readme_jp.txt")  = "readme_jp.txt"
		(Join-Path $RootDir "readme_en.txt")  = "readme_en.txt"
		(Join-Path $RootDir "readme_de.txt")  = "readme_de.txt"
		(Join-Path $RootDir "readme_uk.txt")  = "readme_uk.txt"
		(Join-Path $RootDir "readme_zh.txt")  = "readme_zh.txt"
		(Join-Path $RootDir "LICENSE")        = "LICENSE.txt"
	}
}

$ver = Get-ClclVersion $Version

# Ensure relative paths are not affected by caller's current working directory
if (-not [string]::IsNullOrEmpty($OutDir) -and -not [System.IO.Path]::IsPathRooted($OutDir)) {
	$OutDir = Join-Path $InstallerDir $OutDir
}

if ($Mode -eq "Publish") {
	if ([string]::IsNullOrEmpty($TargetPath) -or -not (Test-Path $TargetPath)) {
		throw "Built installer not found: $TargetPath"
	}
	if ([string]::IsNullOrEmpty($OutDir)) {
		$OutDir = Join-Path $InstallerDir "out"
	}
	New-Item -Path $OutDir -ItemType Directory -Force | Out-Null
	$outPath = Join-Path $OutDir $ver.FileName
	Copy-Item -Path $TargetPath -Destination $outPath -Force
	Write-Host ("Created installer: {0} ({1:N0} bytes)" -f $outPath, (Get-Item $outPath).Length)
	exit 0
}

if ([string]::IsNullOrEmpty($OutDir)) {
	throw "Please specify -OutDir."
}
if ([string]::IsNullOrEmpty($SourceDir)) {
	$SourceDir = Join-Path $RootDir $Configuration
}
New-Item -Path $OutDir -ItemType Directory -Force | Out-Null

# ------------------------------------------------------------------
# Generate version info header
# ------------------------------------------------------------------
$instInfo = @"
/*
 * CLCL Installer
 *
 * instinfo.h
 *
 * Generated by prepare.ps1. Do not edit directly.
 */

#ifndef _INC_CLCL_INSTINFO_H
#define _INC_CLCL_INSTINFO_H

#define INST_VER_MAJOR					$($ver.Major)
#define INST_VER_MINOR					$($ver.Minor)
#define INST_VER_REVISION				$($ver.Revision)
#define INST_VERSION_STR				"$($ver.Text)"
#define INST_FILE_VERSION_STR			"$($ver.Text).0"
#define INST_FILE_NAME					"$($ver.FileName)"

#endif
/* End of source */
"@ -replace "`r`n", "`n" -replace "`n", "`r`n"

# Do not overwrite if content unchanged (avoids unnecessary recompilation)
$instInfoPath = Join-Path $OutDir "instinfo.h"
$utf8Bom = New-Object System.Text.UTF8Encoding $true
if (-not (Test-Path $instInfoPath) -or
	[System.IO.File]::ReadAllText($instInfoPath) -ne $instInfo) {
	[System.IO.File]::WriteAllText($instInfoPath, $instInfo, $utf8Bom)
	Write-Host "Generated instinfo.h (Ver $($ver.Text))"
}

# ------------------------------------------------------------------
# Package installed files into ZIP
# ------------------------------------------------------------------
$targetFiles = Get-TargetFiles $SourceDir
foreach ($from in $targetFiles.Keys) {
	if (-not (Test-Path $from)) {
		throw "File to install not found: $from"
	}
}

# Do not rebuild if all sources are older than the existing ZIP
$zipPath = Join-Path $OutDir "payload.zip"
$latest = ($targetFiles.Keys | ForEach-Object { (Get-Item $_).LastWriteTimeUtc } |
	Sort-Object -Descending | Select-Object -First 1)
if ((Test-Path $zipPath) -and (Get-Item $zipPath).LastWriteTimeUtc -gt $latest) {
	exit 0
}

$stageDir = Join-Path $OutDir "files"
if (Test-Path $stageDir) {
	Remove-Item -Path $stageDir -Recurse -Force
}
New-Item -Path $stageDir -ItemType Directory -Force | Out-Null
foreach ($from in $targetFiles.Keys) {
	$dest = Join-Path $stageDir $targetFiles[$from]
	$copied = $false
	for ($retry = 0; $retry -lt 5 -and -not $copied; $retry++) {
		try {
			Copy-Item -Path $from -Destination $dest -Force
			$copied = $true
		} catch {
			Start-Sleep -Milliseconds 200
		}
	}
	if (-not $copied) {
		Copy-Item -Path $from -Destination $dest -Force
	}
}
if (Test-Path $zipPath) {
	Remove-Item -Path $zipPath -Force
}
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory(
	$stageDir, $zipPath, [System.IO.Compression.CompressionLevel]::Optimal, $false)
Write-Host ("Created payload.zip ({0} files / {1:N0} bytes)" -f `
	$targetFiles.Count, (Get-Item $zipPath).Length)
